version: 2.1
# orbs - reusable packages
orbs:
  docker: circleci/docker@2.1.4
# jobs - set of instructions / functions
jobs:
  publish:
    executor: docker/docker #define the execution environment in which the steps of a job will run
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - docker/build: #build the image
          image: kelvin3118/container-assignment
          tag: v1.0.0
      - docker/push: #pushes the image to the specified account
          image: kelvin3118/container-assignment
          tag: v1.0.0

# workflow - defines what sequence the jobs will run
workflows:
  myflaskapp_workflow:
    jobs:
      - publish
