version: 2.1
# orbs - reusable packages
orbs:
  docker: circleci/docker@2.1.4
# jobs - set of instructions / functions
jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install pip packages
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Test with pytest
          command: python -m pytest
  publish:
    docker:
      - image: cimg/python:3.9
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Logout Docker
          command: docker logout
      - run:
          name: Login Docker
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build Docker image
          command: docker build -t "myflaskapp" .
      - run:
          name: Tag Docker image
          command: docker tag myflaskapp:latest kelvin3118/container-assignment:latest
      - run:
          name: Push Docker image
          command: docker push kelvin3118/container-assignment:latest

# workflow - defines what sequence the jobs will run
workflows:
  myflaskapp_workflow: # workflow name
    jobs:
      - build
